Traceback (most recent call last):
  File "/home/mythezone/miniconda3/envs/web/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/mythezone/miniconda3/envs/web/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mythezone/miniconda3/envs/web/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mythezone/miniconda3/envs/web/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/mythezone/miniconda3/envs/web/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/mythezone/miniconda3/envs/web/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mythezone/miniconda3/envs/web/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from torchview import draw_graph

model_graph = draw_graph(model, input_size=x.shape, expand_nested=True, save_graph=True, filename="torchview", directory=".")

model_graph.visual_graph
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtorchview[39;00m [38;5;28;01mimport[39;00m draw_graph
[1;32m      3[0m model_graph [38;5;241m=[39m draw_graph(model, input_size[38;5;241m=[39mx[38;5;241m.[39mshape, expand_nested[38;5;241m=[39m[38;5;28;01mTrue[39;00m, save_graph[38;5;241m=[39m[38;5;28;01mTrue[39;00m, filename[38;5;241m=[39m[38;5;124m"[39m[38;5;124mtorchview[39m[38;5;124m"[39m, directory[38;5;241m=[39m[38;5;124m"[39m[38;5;124m.[39m[38;5;124m"[39m)
[1;32m      5[0m model_graph[38;5;241m.[39mvisual_graph

[0;31mModuleNotFoundError[0m: No module named 'torchview'

